// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var mandalas;
    mandalas = $(".mandala");
    $("#accelerator").css("transform", "rotate(180deg)");
    $("#accelerator").on("change", function() {
      var actualAnimation, changeRotation, image, rpm, _i, _len;
      $("#turn_on_motor").prop("checked", true);
      rpm = parseInt(60 * (1.0 / parseFloat($('#accelerator').val())));
      $('#velocimeter').text(rpm.toString());
      actualAnimation = "rotation " + ($('#accelerator').val()) + "s infinite linear";
      console.log(actualAnimation);
      for (_i = 0, _len = mandalas.length; _i < _len; _i++) {
        image = mandalas[_i];
        image.style.webkitAnimationPlayState = "paused";
      }
      changeRotation = function() {
        var _j, _len1, _results;
        _results = [];
        for (_j = 0, _len1 = mandalas.length; _j < _len1; _j++) {
          image = mandalas[_j];
          image.style.webkitAnimation = actualAnimation;
          _results.push(image.style.webkitAnimationPlayState = "running");
        }
        return _results;
      };
      return setTimeout(changeRotation, 500);
    });
    return $("#turn_on_motor").on("change", function() {
      var image, state, _i, _len, _results;
      if (this.checked) {
        state = "running";
      } else {
        state = "paused";
      }
      _results = [];
      for (_i = 0, _len = mandalas.length; _i < _len; _i++) {
        image = mandalas[_i];
        _results.push(image.style.webkitAnimationPlayState = state);
      }
      return _results;
    });
  });

}).call(this);
