// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    $("#accelerator").css("transform", "rotate(90deg)");
    $("#accelerator").on("change", function() {
      var actualAnimation, changeRotation, image, rpm, _i, _len, _ref;
      $("#turn_on_motor").prop("checked", true);
      rpm = parseInt(60 * (1.0 / parseFloat($('#accelerator').val())));
      $('#velocimeter').text("" + rpm + " rpm");
      _ref = $(".rotate");
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        image = _ref[_i];
        image.style.webkitAnimationPlayState = "paused";
      }
      actualAnimation = "rotation " + ($('#accelerator').val()) + "s infinite linear";
      changeRotation = function() {
        var _j, _len1, _ref1, _results;
        _ref1 = $(".rotate");
        _results = [];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          image = _ref1[_j];
          image.style.webkitAnimation = actualAnimation;
          _results.push(image.style.webkitAnimationPlayState = "running");
        }
        return _results;
      };
      return setTimeout(changeRotation, 500);
    });
    return $("#turn_on_motor").on("change", function() {
      var image, state, _i, _len, _ref, _results;
      if (this.checked) {
        state = "running";
      } else {
        state = "paused";
      }
      _ref = $(".rotate");
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        image = _ref[_i];
        _results.push(image.style.webkitAnimationPlayState = state);
      }
      return _results;
    });
  });

}).call(this);
