// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var mandalas;
    mandalas = $(".mandala");
    $("#accelerator").css("transform", "rotate(180deg)");
    $("#accelerator").on("change", function() {
      var actualAnimation, changeRotation, pauseMandalas, rpm, runAgain, setAnimation, setAnimationState;
      $("#turn_on_motor").prop("checked", true);
      rpm = parseInt(60 * (1.0 / parseFloat($('#accelerator').val())));
      $('#velocimeter').text(rpm.toString());
      actualAnimation = "rotation " + ($('#accelerator').val()) + "s infinite linear";
      console.log(actualAnimation);
      setAnimationState = function(image, state) {
        return image.style.webkitAnimationPlayState = image.style.mozAnimationPlayState = image.style.oAnimationPlayState = image.style.animationPlayState = state;
      };
      setAnimation = function(image, actualAnimation) {
        return image.style.webkitAnimation = image.style.mozAnimation = image.style.oAnimation = image.style.animation = actualAnimation;
      };
      pauseMandalas = function() {
        var image, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = mandalas.length; _i < _len; _i++) {
          image = mandalas[_i];
          _results.push(setAnimationState(image, "paused"));
        }
        return _results;
      };
      changeRotation = function() {
        var image, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = mandalas.length; _i < _len; _i++) {
          image = mandalas[_i];
          _results.push(setAnimation(image, actualAnimation));
        }
        return _results;
      };
      runAgain = function() {
        var image, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = mandalas.length; _i < _len; _i++) {
          image = mandalas[_i];
          _results.push(setAnimationState(image, "running"));
        }
        return _results;
      };
      setTimeout(pauseMandalas, 1);
      setTimeout(changeRotation, 100);
      return setTimeout(runAgain, 200);
    });
    return $("#turn_on_motor").on("change", function() {
      var image, state, _i, _len, _results;
      if (this.checked) {
        state = "running";
      } else {
        state = "paused";
      }
      _results = [];
      for (_i = 0, _len = mandalas.length; _i < _len; _i++) {
        image = mandalas[_i];
        _results.push(image.style.webkitAnimationPlayState = state);
      }
      return _results;
    });
  });

}).call(this);
