// Generated by CoffeeScript 1.6.3
(function() {
  window.app = angular.module("mandala-app", []);

  window.main = function($scope) {
    var livro, _i, _j, _len, _len1, _ref, _ref1;
    $scope.setAnimationState = function(image, state) {
      return image.style.webkitAnimationPlayState = image.style.mozAnimationPlayState = image.style.oAnimationPlayState = image.style.animationPlayState = state;
    };
    $scope.setAnimation = function(image, actualAnimation) {
      var continueAnimation, pauseAnimation, setAcceleration, setAnimationFor;
      setAnimationFor = function(image, actualAnimation) {
        return image.style.webkitAnimation = image.style.mozAnimation = image.style.oAnimation = image.style.animation = actualAnimation;
      };
      pauseAnimation = function() {
        return $scope.setAnimationState(image, "paused");
      };
      setAcceleration = function() {
        return setAnimationFor(image, actualAnimation);
      };
      continueAnimation = function() {
        return $scope.setAnimationState(image, "running");
      };
      setTimeout(pauseAnimation, 10);
      setTimeout(setAcceleration, 500);
      return setTimeout(continueAnimation, 1000);
    };
    $scope.livros_a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25];
    $scope.livros_b = [1, 2, 3, 4, 5, 6, 7, 8, 9];
    $scope.turn_on_motor = true;
    $scope.accelerator = 0.05;
    $scope.rpm = function() {
      return parseInt(60 * (1.0 / parseFloat($scope.accelerator)));
    };
    $scope.mandalas = [];
    _ref = $scope.livros_a;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      livro = _ref[_i];
      $scope.mandalas.push("mandalas/1/500x500/0" + livro + "b.png");
    }
    _ref1 = $scope.livros_b;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      livro = _ref1[_j];
      $scope.mandalas.push("mandalas/2/500x500/0" + livro + "b.png");
    }
    $scope.img_mandalas = function() {
      var mandala, _k, _len2, _ref2, _results;
      _ref2 = $scope.mandalas;
      _results = [];
      for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
        mandala = _ref2[_k];
        _results.push(document.querySelector("img[src='" + mandala + "']"));
      }
      return _results;
    };
    $scope.velocimeter = function() {
      return $scope.rpm();
    };
    $scope.accelerate = function() {
      var actualAnimation, mandala, _k, _len2, _ref2, _results;
      actualAnimation = "rotation " + $scope.accelerator + "s infinite linear";
      $scope.turn_on_motor = true;
      _ref2 = $scope.img_mandalas();
      _results = [];
      for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
        mandala = _ref2[_k];
        _results.push($scope.setAnimation(mandala, actualAnimation));
      }
      return _results;
    };
    return $scope.switch_on_off = function() {
      var image, state, _k, _len2, _ref2, _results;
      if ($scope.turn_on_motor) {
        state = "running";
      } else {
        state = "paused";
      }
      _ref2 = $scope.img_mandalas();
      _results = [];
      for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
        image = _ref2[_k];
        _results.push($scope.setAnimationState(image, state));
      }
      return _results;
    };
  };

}).call(this);
